"""Incremental selection of explicitly reviewed notice snapshots."""
import argparse
import hashlib
import json
from pathlib import Path
import tempfile

from build_notices import ROOT, load_catalog, load_notices, validate_notice


def notice_digest(notice):
    content = json.dumps(notice, ensure_ascii=False, sort_keys=True, separators=(',', ':'))
    return hashlib.sha256(content.encode('utf-8')).hexdigest()


def select_reviewed(notices, catalog, approvals):
    selected, errors = {}, []
    if not isinstance(approvals, dict) or not approvals:
        return {}, ['La sélection de notices relues doit être un objet non vide']
    for slug in approvals:
        if slug not in catalog:
            errors.append(f'{slug}: identifiant absent du catalogue')
        elif slug not in notices:
            errors.append(f'{slug}: notice relue manquante')
    for slug in catalog:
        if slug not in approvals or slug not in notices:
            continue
        errors.extend(validate_notice(slug, notices[slug]))
        if notice_digest(notices[slug]) != approvals[slug]:
            errors.append(f'{slug}: notice modifiée depuis sa relecture')
        else:
            selected[slug] = notices[slug]
    return ({}, errors) if errors else (selected, [])


def publish_reviewed(notices, catalog, approvals, destination):
    selected, errors = select_reviewed(notices, catalog, approvals)
    if errors:
        return {'errors': errors, 'written': 0}
    content = '// Generated by tools/build_reviewed_notices.py from reviewed snapshots.\n'
    content += 'window.FF_NOTICES = ' + json.dumps(selected, ensure_ascii=False, indent=2) + ';\n'
    destination = Path(destination)
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8', newline='\n',
                                         dir=destination.parent, prefix='.notices-', delete=False) as stream:
            temporary = Path(stream.name)
            stream.write(content)
        temporary.replace(destination)
    finally:
        if temporary is not None and temporary.exists():
            temporary.unlink()
    return {'errors': [], 'written': len(selected)}


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--manifest', type=Path, default=ROOT / 'data/reviewed-notices.json')
    parser.add_argument('--output', type=Path, default=ROOT / 'js/notices.js')
    parser.add_argument('--check', action='store_true', help='Validate reviewed snapshots without writing')
    args = parser.parse_args(argv)
    try:
        approvals = json.loads(args.manifest.read_text(encoding='utf-8'))
        notices, errors = load_notices()
        catalog = load_catalog()
        if errors:
            print(json.dumps({'errors': errors}, ensure_ascii=False))
            return 1
        if args.check:
            selected, errors = select_reviewed(notices, catalog, approvals)
            result = {'errors': errors, 'eligible': len(selected), 'written': 0}
        else:
            result = publish_reviewed(notices, catalog, approvals, args.output)
        print(json.dumps(result, ensure_ascii=False))
        return int(bool(result['errors']))
    except (OSError, ValueError) as exc:
        print(json.dumps({'errors': [str(exc)]}, ensure_ascii=False))
        return 1


if __name__ == '__main__':
    raise SystemExit(main())
